theme: jekyll-theme-slate
title: [Data Science for Smart Manufacturing and Healthcare Workshop]
description: [<a href="https://www.siam.org/conferences/cm/program/workshops/sdm23-workshops">DS2-MH Workshop</a> at <a href="https://www.siam.org/conferences/cm/conference/sdm24">SDM24</a> April 18-20,2024 Westin Houston, Memorial City
Houston, Texas, U.S.]
lang: "en
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
