theme: jekyll-theme-slate
title: [Data Science for Smart Manufacturing and Healthcare]
description: [DS<sup>2</sup>-MH Workshop at <a href="https://www.siam.org/conferences/cm/conference/sdm23">SDM23</a>, April 27, 2023]
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
